version: "3.8"
services:
  cmdapi:
    container_name: cmdapi
    image: andreirotariu/cmdapi:0.1.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    ports:
      - "9991:9991"
    restart: unless-stopped
